export const SESSION_QUERY_STALE_TIME_MS = 5 * 60_000;
export const SERVERS_QUERY_STALE_TIME_MS = 10_000;
export const SERVERS_QUERY_REFETCH_INTERVAL_MS = 15_000;
export const CATEGORIES_QUERY_STALE_TIME_MS = 30_000;
